import '../../../core/utils/constants.dart';

class SkillCatalogEntry {
  final String id;
  final String className;
  final String treeName;
  final String name;
  final int maxRank;
  final int pointCostPerRank;
  final String type; // 'active', 'passive', or 'technique'
  final List<String> prerequisiteSkillIds;

  const SkillCatalogEntry({
    required this.id,
    required this.className,
    required this.treeName,
    required this.name,
    this.maxRank = 1,
    this.pointCostPerRank = 1,
    required this.type,
    this.prerequisiteSkillIds = const [],
  });
}

// Source of truth (skills + types):
//   https://duneawakening.wiki.fextralife.com/Skill+Trees
// Source of truth (sub-tree groupings):
//   https://www.pcgamesn.com/dune-awakening/skills
//
// Wiki types map to catalog `type` as: Ability → 'active',
// Passive → 'passive', Technique → 'technique'. Abilities and Techniques
// are both equipped (3 slots each per class) — Abilities trigger from the
// ability bar, Techniques only take effect while equipped.
const skillCatalog = [
  // ═══ Bene Gesserit ═══════════════════════════════════════════════════════
  // Weirding Way
  SkillCatalogEntry(
    id: 'benegesserit-bindu-dodge',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Bindu Dodge',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-bindu-sprint',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Bindu Sprint',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-blade-damage-bene-gesserit',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Blade Damage (Bene Gesserit)',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-manipulate-instability',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Manipulate Instability',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-prana-bindu-strikes',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Prana-Bindu Strikes',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-short-blade-damage',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Short Blade Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-weirding-step',
    className: AppConstants.classBeneGesserit,
    treeName: 'Weirding Way',
    name: 'Weirding Step',
    maxRank: 3,
    type: 'active',
  ),
  // The Voice
  SkillCatalogEntry(
    id: 'benegesserit-compel',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Compel',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-ignore',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Ignore',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-rapid-register',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Rapid Register',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-screech',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Screech',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-stop',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Stop',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-voice-training',
    className: AppConstants.classBeneGesserit,
    treeName: 'The Voice',
    name: 'Voice Training',
    maxRank: 3,
    type: 'passive',
  ),
  // Body Control
  SkillCatalogEntry(
    id: 'benegesserit-litany-against-fear',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Litany Against Fear',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-metabolize-poison',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Metabolize Poison',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-poison-tolerance',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Poison Tolerance',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-prana-bindu-stability',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Prana-Bindu Stability',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-recovery',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Recovery',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-self-healing',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Self-Healing',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-sun-tolerance',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Sun Tolerance',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-trauma-recovery',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Trauma Recovery',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'benegesserit-vitality',
    className: AppConstants.classBeneGesserit,
    treeName: 'Body Control',
    name: 'Vitality',
    maxRank: 3,
    type: 'passive',
  ),

  // ═══ Mentat ══════════════════════════════════════════════════════════════
  // Mental Calculus
  SkillCatalogEntry(
    id: 'mentat-exploit-weakness',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Exploit Weakness',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'mentat-garment-keeper',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Garment Keeper',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-marksman',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Marksman',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'mentat-pistol-damage',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Pistol Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-ranged-damage-mentat',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Ranged Damage (Mentat)',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-rifle-damage',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Rifle Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-shield-overcharge',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Shield Overcharge',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-tailoring',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'Tailoring',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-the-sentinel',
    className: AppConstants.classMentat,
    treeName: 'Mental Calculus',
    name: 'The Sentinel',
    maxRank: 3,
    type: 'active',
  ),
  // Assassination
  SkillCatalogEntry(
    id: 'mentat-assassins-shot',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: "Assassin's Shot",
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-headshot-damage',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Headshot Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'mentat-hunter-seeker',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Hunter-Seeker',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-poison-capsule',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Poison Capsule',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-poison-mine',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Poison Mine',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-poison-tooth',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Poison Tooth',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'mentat-stunner',
    className: AppConstants.classMentat,
    treeName: 'Assassination',
    name: 'Stunner',
    maxRank: 3,
    type: 'active',
  ),
  // Tactician
  SkillCatalogEntry(
    id: 'mentat-anti-gravity-mine',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Anti-gravity Mine',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-gravity-mine',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Gravity Mine',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-iron-will',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Iron Will',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'mentat-shield-wall',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Shield Wall',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-solido-decoy',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Solido Decoy',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'mentat-source-of-power',
    className: AppConstants.classMentat,
    treeName: 'Tactician',
    name: 'Source of Power',
    maxRank: 3,
    type: 'active',
  ),

  // ═══ Planetologist ═══════════════════════════════════════════════════════
  // Scientist
  SkillCatalogEntry(
    id: 'planetologist-compaction',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Compaction',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-conservation-of-energy',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Conservation of Energy',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'planetologist-cutteray-mining',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Cutteray Mining',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-deep-analysis',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Deep Analysis',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-dew-gathering',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Dew Gathering',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-overcharge',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Overcharge',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-rerouting',
    className: AppConstants.classPlanetologist,
    treeName: 'Scientist',
    name: 'Rerouting',
    maxRank: 3,
    type: 'passive',
  ),
  // Explorer
  SkillCatalogEntry(
    id: 'planetologist-cartographer',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Cartographer',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-mountaineer',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Mountaineer',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-scanner-mastery',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Scanner Mastery',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-spice-surveyor',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Spice Surveyor',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-stillsuit-seals',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Stillsuit Seals',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-suspensor-pad',
    className: AppConstants.classPlanetologist,
    treeName: 'Explorer',
    name: 'Suspensor Pad',
    maxRank: 3,
    type: 'active',
  ),
  // Mechanic
  SkillCatalogEntry(
    id: 'planetologist-fuel-efficient-driver',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Fuel Efficient Driver',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-fuel-efficient-pilot',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Fuel Efficient Pilot',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-heat-management',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Heat Management',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-sandcrawler-yield',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Sandcrawler Yield',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-vehicle-mining',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Vehicle Mining',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-vehicle-repair',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Vehicle Repair',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'planetologist-vehicle-scanning',
    className: AppConstants.classPlanetologist,
    treeName: 'Mechanic',
    name: 'Vehicle Scanning',
    maxRank: 3,
    type: 'passive',
  ),

  // ═══ Trooper ═════════════════════════════════════════════════════════════
  // Gunnery
  SkillCatalogEntry(
    id: 'trooper-center-of-mass',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Center of Mass',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'trooper-disruptor-damage',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Disruptor Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-energy-capsule',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Energy Capsule',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-field-maintenance',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Field Maintenance',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-gunsmith',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Gunsmith',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-heavy-weapon-damage',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Heavy Weapon Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-ranged-damage-trooper',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Ranged Damage (Trooper)',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-scattergun-damage',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Scattergun Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-underslung-agility',
    className: AppConstants.classTrooper,
    treeName: 'Gunnery',
    name: 'Underslung Agility',
    maxRank: 3,
    type: 'technique',
  ),
  // Suspensor Training
  SkillCatalogEntry(
    id: 'trooper-anti-gravity-field',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Anti-gravity Field',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-collapse-grenade',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Collapse Grenade',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-death-from-above',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Death from Above',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'trooper-gravity-field',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Gravity Field',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-suspensor-blast',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Suspensor Blast',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-suspensor-dash',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Suspensor Dash',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'trooper-suspensor-efficiency',
    className: AppConstants.classTrooper,
    treeName: 'Suspensor Training',
    name: 'Suspensor Efficiency',
    maxRank: 3,
    type: 'passive',
  ),
  // Tactical Tech
  SkillCatalogEntry(
    id: 'trooper-assault-seeker',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Assault Seeker',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-attractor-field',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Attractor Field',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-battle-hardened',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Battle Hardened',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'trooper-explosive-grenade',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Explosive Grenade',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'trooper-reflexive-reload',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Reflexive Reload',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'trooper-shigawire-claw',
    className: AppConstants.classTrooper,
    treeName: 'Tactical Tech',
    name: 'Shigawire Claw',
    maxRank: 3,
    type: 'active',
  ),

  // ═══ Swordmaster ═════════════════════════════════════════════════════════
  // The Blade
  SkillCatalogEntry(
    id: 'swordmaster-blade-damage-swordmaster',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Blade Damage (Swordmaster)',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-dance-of-blades',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Dance of Blades',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-eye-of-the-storm',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Eye of the Storm',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-foil',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Foil',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-long-blade-damage',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Long Blade Damage',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-precise-parry',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Precise Parry',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-retaliate',
    className: AppConstants.classSwordmaster,
    treeName: 'The Blade',
    name: 'Retaliate',
    maxRank: 3,
    type: 'active',
  ),
  // The Will
  SkillCatalogEntry(
    id: 'swordmaster-bleed-tolerance',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Bleed Tolerance',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-confidence',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Confidence',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-deflection',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Deflection',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-reckless-lunge',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Reckless Lunge',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-solid-stance',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Solid Stance',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-thrive-on-danger',
    className: AppConstants.classSwordmaster,
    treeName: 'The Will',
    name: 'Thrive on Danger',
    maxRank: 3,
    type: 'technique',
  ),
  // The Way
  SkillCatalogEntry(
    id: 'swordmaster-crippling-strike',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Crippling Strike',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-desert-conditioning',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Desert Conditioning',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-disciplined-breathing',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Disciplined Breathing',
    maxRank: 3,
    type: 'technique',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-field-medicine',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Field Medicine',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-general-conditioning',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'General Conditioning',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-inspiration',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Inspiration',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-knee-charge',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Knee Charge',
    maxRank: 3,
    type: 'active',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-optimized-hydration',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Optimized Hydration',
    maxRank: 3,
    type: 'passive',
  ),
  SkillCatalogEntry(
    id: 'swordmaster-prescient-strike',
    className: AppConstants.classSwordmaster,
    treeName: 'The Way',
    name: 'Prescient Strike',
    maxRank: 3,
    type: 'passive',
  ),
];
